In [3]:
import pandas as pd
import numpy as np
from numpy.linalg import inv

### Q1

In [4]:
pd.__version__

'2.3.1'

### Q2

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

In [6]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [7]:
df.shape

(9704, 11)

### Q3

In [8]:
df.fuel_type.unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [9]:
df.fuel_type.nunique()

2

### Q4

In [10]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

### Q5

In [12]:
df.query("origin=='Asia'")['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

### Q6

In [13]:
df['horsepower'].median()

np.float64(149.0)

In [14]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [15]:
df['horsepower'].fillna(152).median()

np.float64(152.0)

### Q7

In [21]:
X = df.query("origin=='Asia'")[['vehicle_weight', 'model_year']].to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       ...,
       [2545.07013932, 2012.        ],
       [3107.42781965, 2005.        ],
       [2908.04347736, 2005.        ]], shape=(3247, 2))

In [23]:
X = X[:7]
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [24]:
XTX = np.dot(X.T,X)

In [25]:
inv(XTX)

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [26]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [27]:
w = np.dot(inv(XTX), X.T)

In [28]:
w = np.dot(w,y)

In [29]:
w

array([0.01386421, 0.5049067 ])

In [30]:
w.sum()

np.float64(0.5187709081074016)